In [1]:
import numpy as np
import pandas as pd
import os
import lightgbm as lgb
from sklearn.metrics import accuracy_score




os.getcwd()
os.chdir('/Users/ting/Desktop/kaggle_Zillow_Prize/')

讀取資料

In [2]:
train = pd.read_csv('train_2017.csv')
prop = pd.read_csv('properties_2017.csv')
samp = pd.read_csv('sample_submission.csv')

/Users/ting/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

lightgbm

In [3]:
#set training data
train_t = train.merge(prop, how = 'left', on = 'parcelid')
train_x = train_t.drop(['logerror'], axis=1)
train_y = train_t['logerror'].values

In [4]:
#尋找na超過95%的欄位
train_x_test_nanu = train_x.fillna(0)
dr_na_cl = []
for i in train_x_test_nanu.dtypes.index.values:
    if (len(train_x_test_nanu.ix[train_x_test_nanu.ix[:, i] == 0, i]))/len(train_x_test_nanu[[i]]) > 0.95:
        print(i)
        dr_na_cl.append(i)
dr_na_cl

/Users/ting/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """

architecturalstyletypeid
basementsqft
buildingclasstypeid
decktypeid
finishedsquarefeet13
finishedsquarefeet15
finishedsquarefeet6
hashottuborspa
poolsizesum
pooltypeid10
pooltypeid2
storytypeid
typeconstructiontypeid
yardbuildingsqft17
yardbuildingsqft26
fireplaceflag
taxdelinquencyflag
taxdelinquencyyear

['architecturalstyletypeid',
 'basementsqft',
 'buildingclasstypeid',
 'decktypeid',
 'finishedsquarefeet13',
 'finishedsquarefeet15',
 'finishedsquarefeet6',
 'hashottuborspa',
 'poolsizesum',
 'pooltypeid10',
 'pooltypeid2',
 'storytypeid',
 'typeconstructiontypeid',
 'yardbuildingsqft17',
 'yardbuildingsqft26',
 'fireplaceflag',
 'taxdelinquencyflag',
 'taxdelinquencyyear']

In [5]:
#刪除空直超過95%的欄位
train_x = train_x.drop(dr_na_cl, axis = 1)

In [6]:
#找出objects的欄位
train_x.dtypes[train_x.dtypes == 'object'].index.values
#array(['transactiondate', 'propertycountylandusecode', 'propertyzoningdesc'], dtype=object)
#處理transactiondate
train_x['transactiondate'] = train_x['transactiondate'].str.extract('(\d\d\d\d/\d)')
train_x['transactiondate']= train_x['transactiondate'].replace(
    ['2017/1', '2017/2', '2017/3', '2017/4', '2017/5', '2017/6', '2017/7', '2017/8', '2017/9'], 
    ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep'])
train_x['transactiondate']

#處理propertycountylandusecode 跟此欄位相關欄位也是空值，所以無法借用來處理
train_x['propertycountylandusecode'].isnull = 'None'

#處理propertyzoningdesc'
pd.DataFrame(train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid']).to_csv('propertylandusetypeid_col_uni.csv')
train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'].value_counts()
#246~8 260 261 263 265 266 269 275
#246
train_x.loc[train_x['propertylandusetypeid'] == 246, 'propertyzoningdesc'].value_counts()
#LAR2
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 246, 'propertyzoningdesc']  = 'LAR2'
#247
train_x.loc[train_x['propertylandusetypeid'] == 247, 'propertyzoningdesc'].value_counts()
#LAR2
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 247, 'propertyzoningdesc']  = 'LAR2'
#248
train_x.loc[train_x['propertylandusetypeid'] == 248, 'propertyzoningdesc'].value_counts()
#LARD1.5
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 248, 'propertyzoningdesc']  = 'LARD1.5'
#260
train_x.loc[train_x['propertylandusetypeid'] == 260, 'propertyzoningdesc'].value_counts()
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 260, 'propertyzoningdesc']  = 'LAR3'
#261
train_x.loc[train_x['propertylandusetypeid'] == 261, 'propertyzoningdesc'].value_counts()
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 261, 'propertyzoningdesc']  = 'LAR1'
#263
train_x.loc[train_x['propertylandusetypeid'] == 263, 'propertyzoningdesc'].value_counts()
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 263, 'propertyzoningdesc']  = 'LCA21*' 
#265
train_x.loc[train_x['propertylandusetypeid'] == 265, 'propertyzoningdesc'].value_counts()
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 265, 'propertyzoningdesc']  = 'None' 
#266
train_x.loc[train_x['propertylandusetypeid'] == 266, 'propertyzoningdesc'].value_counts()
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 266, 'propertyzoningdesc']  = 'LAR3' 
#269
train_x.loc[train_x['propertylandusetypeid'] == 269, 'propertyzoningdesc'].value_counts()
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 269, 'propertyzoningdesc']  = 'SCUR2' 
#275
train_x.loc[train_x['propertylandusetypeid'] == 275, 'propertyzoningdesc'].value_counts()
train_x[train_x['propertyzoningdesc'].isnull()].loc[train_x.loc[train_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 275, 'propertyzoningdesc']  = 'None'

/Users/ting/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """
/Users/ting/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [7]:
#用0填充欄位,get dummies
train_x = train_x.fillna(0)
train_x = pd.get_dummies(train_x)

In [8]:
train_col = train_x.columns
train_col

Index(['parcelid', 'airconditioningtypeid', 'bathroomcnt', 'bedroomcnt',
       'buildingqualitytypeid', 'calculatedbathnbr',
       'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet',
       'finishedsquarefeet12', 'finishedsquarefeet50',
       ...
       'propertyzoningdesc_WVRPD12000', 'propertyzoningdesc_WVRPD12U*',
       'propertyzoningdesc_WVRPD12U-R', 'propertyzoningdesc_WVRPD17U*',
       'propertyzoningdesc_WVRPD18U*', 'propertyzoningdesc_WVRPD40000',
       'propertyzoningdesc_WVRPD4OOOO', 'propertyzoningdesc_WVRPD56*',
       'propertyzoningdesc_WVRR', 'propertyzoningdesc_WVRR1-RPD1'],
      dtype='object', length=2031)

In [9]:
#設置lgb的data set
train_x = np.array(train_x)
lgb_dSet = lgb.Dataset(train_x, label = train_y)

In [10]:
#訓練模型
params = {}
lgn_clf = lgb.train(params, lgb_dSet)

In [13]:
lgn_clf_pre = lgn_clf.predict(train_x)

In [15]:
lgn_clf_pre

array([ 0.02836505,  0.01476943,  0.01463544, ...,  0.03292939,
        0.08446339,  0.02055339])

In [19]:
#計算精準度
np.exp((train_y - lgn_clf_pre).mean())
#accuracy_score(train_y, lgn_clf_pre)

0.99999999998541234

In [12]:
#設置test data
samp['parcelid'] = samp['ParcelId']
test_x = samp.merge(prop, on='parcelid', how='left')
test_x

,ParcelId,201610,201611,201612,201710,201711,201712,parcelid,airconditioningtypeid,architecturalstyletypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,0,0,0,0,0,0,10754147,NaN,NaN,...,NaN,NaN,NaN,9.0,2016.0,9.0,NaN,NaN,NaN,NaN
1,10759547,0,0,0,0,0,0,10759547,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,0,0,0,0,0,0,10843547,NaN,NaN,...,1.0,NaN,660680.0,1434941.0,2016.0,774261.0,20800.37,NaN,NaN,NaN
3,10859147,0,0,0,0,0,0,10859147,NaN,NaN,...,1.0,NaN,580059.0,1174475.0,2016.0,594416.0,14557.57,NaN,NaN,NaN
4,10879947,0,0,0,0,0,0,10879947,NaN,NaN,...,1.0,NaN,196751.0,440101.0,2016.0,243350.0,5725.17,NaN,NaN,NaN
5,10898347,0,0,0,0,0,0,10898347,NaN,NaN,...,1.0,NaN,179072.0,287634.0,2016.0,108562.0,3661.28,NaN,NaN,NaN
6,10933547,0,0,0,0,0,0,10933547,NaN,NaN,...,NaN,NaN,404013.0,563029.0,2016.0,159016.0,6773.34,NaN,NaN,NaN
7,10940747,0,0,0,0,0,0,10940747,NaN,NaN,...,1.0,NaN,103553.0,698984.0,2016.0,595431.0,7857.84,NaN,NaN,NaN
8,10954547,0,0,0,0,0,0,10954547,NaN,NaN,...,NaN,NaN,NaN,9.0,2016.0,9.0,NaN,NaN,NaN,NaN
9,10976347,0,0,0,0,0,0,10976347,NaN,NaN,...,1.0,NaN,221771.0,265184.0,2016.0,43413.0,4054.76,NaN,NaN,NaN
10,11073947,0,0,0,0,0,0,11073947,NaN,NaN,...,1.0,NaN,249582.0,436767.0,2016.0,187185.0,6014.18,NaN,NaN,NaN
11,11114347,0,0,0,0,0,0,11114347,NaN,NaN,...,NaN,NaN,NaN,9.0,2016.0,9.0,NaN,NaN,NaN,NaN
12,11116947,0,0,0,0,0,0,11116947,NaN,NaN,...,NaN,NaN,NaN,171200.0,2016.0,171200.0,4690.68,NaN,NaN,NaN
13,11142747,0,0,0,0,0,0,11142747,NaN,NaN,...,NaN,NaN,NaN,4265.0,2015.0,4265.0,NaN,NaN,NaN,NaN
14,11193347,0,0,0,0,0,0,11193347,NaN,NaN,...,NaN,NaN,NaN,10.0,2016.0,10.0,NaN,NaN,NaN,NaN
15,11215747,0,0,0,0,0,0,11215747,NaN,NaN,...,NaN,NaN,NaN,10.0,2016.0,10.0,NaN,NaN,NaN,NaN
16,11229347,0,0,0,0,0,0,11229347,NaN,NaN,...,NaN,NaN,NaN,2108.0,2016.0,2108.0,174.21,NaN,NaN,NaN
17,11287347,0,0,0,0,0,0,11287347,NaN,NaN,...,1.0,NaN,33151.0,63374.0,2016.0,30223.0,2330.24,NaN,NaN,NaN
18,11288547,0,0,0,0,0,0,11288547,NaN,NaN,...,NaN,NaN,176653.0,314727.0,2016.0,138074.0,4162.56,NaN,NaN,NaN
19,11324547,0,0,0,0,0,0,11324547,1.0,NaN,...,NaN,NaN,222321.0,296425.0,2016.0,74104.0,6941.39,NaN,NaN,NaN
20,11391347,0,0,0,0,0,0,11391347,NaN,NaN,...,1.0,NaN,200612.0,511433.0,2016.0,310821.0,6840.34,NaN,NaN,NaN
21,11395747,0,0,0,0,0,0,11395747,NaN,NaN,...,1.0,NaN,36423.0,50689.0,2016.0,14266.0,1522.08,NaN,NaN,NaN
22,11404347,0,0,0,0,0,0,11404347,NaN,NaN,...,1.0,NaN,111677.0,365489.0,2016.0,253812.0,3703.54,Y,13.0,NaN
23,11405747,0,0,0,0,0,0,11405747,NaN,NaN,...,1.0,NaN,42556.0,184437.0,2016.0,141881.0,2992.02,NaN,NaN,NaN
24,11417147,0,0,0,0,0,0,11417147,NaN,NaN,...,1.0,NaN,45644.0,135755.0,2016.0,90111.0,2797.70,NaN,NaN,NaN
25,11457547,0,0,0,0,0,0,11457547,NaN,NaN,...,NaN,NaN,NaN,124.0,2016.0,124.0,NaN,NaN,NaN,NaN
26,11488147,0,0,0,0,0,0,11488147,NaN,NaN,...,NaN,NaN,271704.0,831224.0,2016.0,559520.0,10455.41,NaN,NaN,NaN
27,11520747,0,0,0,0,0,0,11520747,NaN,NaN,...,1.0,NaN,207923.0,798579.0,2016.0,590656.0,11304.81,NaN,NaN,NaN
28,11524947,0,0,0,0,0,0,11524947,1.0,NaN,...,NaN,NaN,232897.0,357568.0,2016.0,124671.0,6165.36,NaN,NaN,NaN
29,11544747,0,0,0,0,0,0,11544747,1.0,NaN,...,NaN,NaN,339532.0,847770.0,2016.0,508238.0,10244.94,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985187,167636430,0,0,0,0,0,0,167636430,NaN,NaN,...,NaN,NaN,NaN,144974.0,2016.0,144974.0,3235.44,NaN,NaN,NaN
2985188,167690630,0,0,0,0,0,0,167690630,NaN,NaN,...,NaN,NaN,NaN,NaN,2016.0,NaN,377.54,NaN,NaN,NaN
2985189,167636630,0,0,0,0,0,0,167636630,NaN,NaN,...,NaN,NaN,NaN,208556.0,2016.0,208556.0,3429.09,NaN,NaN,NaN
2985190,10834030,0,0,0,0,0,0,10834030,1.0,NaN,...,NaN,NaN,282239.0,705598.0,2016.0,423359.0,8637.81,NaN,NaN,NaN
2985191,167637430,0,0,0,0,0,0,167637430,NaN,NaN,...,NaN,NaN,101525.0,304575.0,2016.0,203050.0,3850.32,NaN,NaN,NaN
2985192,167637630,0,0,0,0,0,0,167637630,NaN,NaN,...,NaN,NaN,4629733.0,9550528.0,2016.0,4920795.0,116269.60,NaN,NaN,NaN
2985193,167637230,0,0,0,0,0,0,167637230,1.0,NaN,...,NaN,NaN,930000.0,1239000.0,2016.0,309000.0,15012.95,NaN,NaN,NaN
2985194,11645030,0,0,0,0,0,0,11645030,1.0,NaN,...,NaN,NaN,109000.0,522000.0,2016.0,413000.0,6286.20,NaN,NaN,6.037265e+13
2985195,167689030,0,0,0,0,0,0,167689030,NaN,NaN,...,NaN,NaN,257000.0,537000.0,2016.0,280000.0,6638.52,NaN,NaN,NaN
2985196,167638630,0,0,0,0,0,0,167638630,NaN,NaN,...,NaN,NaN,NaN,285623.0,2016.0,285623.0,3583.82,NaN,NaN,NaN
2985197,167638430,0,0,0,0,0,0,167638430,NaN,NaN,...,NaN,NaN,345000.0,460000.0,2016.0,115000.0,5334.92,NaN,NaN,NaN
2985198,14342030,0,0,0,0,0,0,14342030,NaN,NaN,...,NaN,NaN,1079124.0,2309323.0,2016.0,1230199.0,31402.56,NaN,NaN,NaN
2985199,167638230,0,0,0,0,0,0,167638230,NaN,NaN,...,NaN,NaN,399231.0,983651.0,2016.0,584420.0,11274.55,NaN,NaN,NaN
2985200,167637830,0,0,0,0,0,0,167637830,1.0,NaN,...,NaN,NaN,74214.0,143981.0,2016.0,69767.0,1930.37,NaN,NaN,NaN
2985201,167639230,0,0,0,0,0,0,167639230,1.0,NaN,...,NaN,NaN,500000.0,825000.0,2016.0,325000.0,9420.39,NaN,NaN,NaN
2985202,14341030,0,0,0,0,0,0,14341030,NaN,NaN,...,NaN,NaN,826200.0,1720635.0,2016.0,894435.0,24209.10,NaN,NaN,NaN
2985203,14341630,0,0,0,0,0,0,14341630,NaN,NaN,...,NaN,NaN,543361.0,1236570.0,2016.0,693209.0,17652.22,NaN,NaN,NaN
2985204,14367630,0,0,0,0,0,0,14367630,NaN,NaN,...,NaN,NaN,335118.0,464559.0,2016.0,129441.0,5716.98,NaN,NaN,NaN
2985205,167638830,0,0,0,0,0,0,167638830,1.0,NaN,...,NaN,NaN,41380.0,68966.0,2016.0,27586.0,1160.92,NaN,NaN,NaN
2985206,12572230,0,0,0,0,0,0,12572230,1.0,NaN,...,NaN,NaN,239900.0,322742.0,2016.0,82842.0,4025.03,NaN,NaN,6.037572e+13
2985207,14460030,0,0,0,0,0,0,14460030,NaN,NaN,...,NaN,NaN,330567.0,645680.0,2016.0,315113.0,10120.48,NaN,NaN,6.059032e+13
2985208,14284830,0,0,0,0,0,0,14284830,NaN,NaN,...,NaN,NaN,NaN,154639.0,2016.0,154639.0,5545.60,NaN,NaN,NaN
2985209,14285230,0,0,0,0,0,0,14285230,NaN,NaN,...,NaN,NaN,715463.0,870101.0,2016.0,154638.0,16419.90,NaN,NaN,NaN
2985210,14455630,0,0,0,0,0,0,14455630,NaN,NaN,...,NaN,NaN,827163.0,1125779.0,2016.0,298616.0,18682.22,NaN,NaN,6.059032e+13
2985211,11117630,0,0,0,0,0,0,11117630,1.0,NaN,...,NaN,NaN,507625.0,774635.0,2016.0,267010.0,15220.42,NaN,NaN,6.037920e+13
2985212,168176230,0,0,0,0,0,0,168176230,NaN,NaN,...,NaN,NaN,110245.0,226900.0,2016.0,116655.0,3035.26,NaN,NaN,NaN
2985213,14273630,0,0,0,0,0,0,14273630,NaN,NaN,...,NaN,NaN,378466.0,762157.0,2016.0,383691.0,8653.10,NaN,NaN,NaN
2985214,168040630,0,0,0,0,0,0,168040630,NaN,NaN,...,NaN,NaN,201575.0,483188.0,2016.0,281613.0,5671.40,NaN,NaN,NaN
2985215,168040830,0,0,0,0,0,0,168040830,NaN,NaN,...,NaN,NaN,347863.0,578621.0,2016.0,230758.0,5894.36,NaN,NaN,NaN
2985216,168040430,0,0,0,0,0,0,168040430,NaN,NaN,...,NaN,NaN,257111.0,700947.0,2016.0,443836.0,10271.38,NaN,NaN,NaN

In [13]:
#刪除空直超過95%的欄位
test_x = test_x.drop(dr_na_cl, axis = 1)

In [14]:
#處理obj欄位
test_x['propertycountylandusecode'].isnull = 'None'

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 246, 'propertyzoningdesc']  = 'LAR2'

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 247, 'propertyzoningdesc']  = 'LAR2'

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 248, 'propertyzoningdesc']  = 'LARD1.5'

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 260, 'propertyzoningdesc']  = 'LAR3'

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 261, 'propertyzoningdesc']  = 'LAR1'

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 263, 'propertyzoningdesc']  = 'LCA21*' 

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 265, 'propertyzoningdesc']  = 'None' 

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 266, 'propertyzoningdesc']  = 'LAR3' 

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 269, 'propertyzoningdesc']  = 'SCUR2' 

test_x[test_x['propertyzoningdesc'].isnull()].loc[test_x.loc[test_x['propertyzoningdesc'].isnull(), 'propertylandusetypeid'] == 275, 'propertyzoningdesc']  = 'None'

/Users/ting/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [ ]:
#用0填充欄位,get dummies
test_x = test_x.fillna(0)
test_x = pd.get_dummies(test_x)

In [ ]:
#設置lgb的data set
test_x = np.array(test_x)

In [ ]:
lgb_pre = lgn_clf.predict(test_x)

In [ ]:
pd.DataFrame(lgb_pre).to_csv('lgb_pre.csv')